import { existsSync } from 'node:fs'
import { readdir } from 'node:fs/promises'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import type { ComponentDocsMeta } from './types.js'

function assertValidMeta(meta: ComponentDocsMeta, expectedSlug: string): void {
  if (meta.slug !== expectedSlug) {
    throw new Error(`Meta slug mismatch in "${expectedSlug}": received "${meta.slug}"`)
  }
  if (!meta.name || !meta.description || !meta.category) {
    throw new Error(`Meta for "${expectedSlug}" is missing required fields`)
  }
}

export async function collectComponentDocs(registrySourceDir: string): Promise<ComponentDocsMeta[]> {
  const componentsDir = join(registrySourceDir, 'components')
  const entries = await readdir(componentsDir, { withFileTypes: true })
  const componentSlugs = entries
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort()

  const docs: ComponentDocsMeta[] = []

  for (const slug of componentSlugs) {
    const metaPath = join(componentsDir, slug, 'meta.ts')
    if (!existsSync(metaPath)) {
      throw new Error(`Missing metadata file: ${metaPath}`)
    }

    const moduleUrl = `${pathToFileURL(metaPath).href}?slug=${encodeURIComponent(slug)}`
    const moduleExports = await import(moduleUrl)
    const meta = moduleExports.meta as ComponentDocsMeta | undefined

    if (!meta) {
      throw new Error(`Metadata module "${metaPath}" does not export "meta"`)
    }

    assertValidMeta(meta, slug)
    docs.push(meta)
  }

  return docs.sort((a, b) => a.slug.localeCompare(b.slug))
}

export function renderWebComponentDocsModule(docs: ComponentDocsMeta[]): string {
  const sortedDocs = [...docs].sort((a, b) => a.slug.localeCompare(b.slug))
  const body = JSON.stringify(sortedDocs, null, 2)

  return `// This file is auto-generated by packages/registry/scripts/generate-web-component-docs.ts
// Do not edit manually.

export type ComponentCategory = 'feedback' | 'input' | 'display'

export interface ComponentPropMeta {
  name: string
  type: string
  default: string
  description: string
}

export interface ComponentDocsMeta {
  slug: string
  name: string
  description: string
  category: ComponentCategory
  usage: string
  props: ComponentPropMeta[]
}

export const componentDocs: ComponentDocsMeta[] = ${body}
`
}
